MLanguage/mlang

examples/python/backend_tests/Makefile, src/mlang/backend_compilers/bir_to_python.ml
=> Fix python backend for 2019

Makefile, src/dune
=> static make

src/mlang/m_frontend/dune, src/mlang/m_frontend/mparser.mly, src/mlang/mpp_frontend/dune
Menhir had some trouble determining precedence in chains of boolean binary operators.
=> Fixed remaining M parser conflicts

examples/c/m_value.h, src/mlang/backend_compilers/bir_to_c.ml
=> Header files

.github/workflows/static-build.yml
Should fix failing static builds with Github CI
=> Use Ocaml musl compiler

src/mlang/driver.ml, src/mlang/m_ir/mir_dependency_graph.ml, src/mlang/utils/cli.ml
=> Reactivate cyclic dependency check

src/mlang/backend_compilers/bir_to_dgfip_c.ml, src/mlang/backend_compilers/bir_to_dgfip_c.mli, src/mlang/backend_compilers/dgfip_gen_files.ml, src/mlang/backend_compilers/dgfip_varid.ml, src/mlang/driver.ml, src/mlang/m_frontend/format_mast.mli, src/mlang/m_ir/mir.mli
This kind of resurrects #59 and links it properly with #97.
=> Properly link DGFiP-specific options and auxiliary file generation (resurrects #59)

mlang.opam, src/mlang/backend_ir/bir_interface.ml, src/mlang/m_frontend/mast_to_mir.ml, src/mlang/m_frontend/mast_to_mir.mli
=> Substitute constants by their value in Mast to Mir transformation

Makefile, examples/java/Makefile, examples/java/src/com/mlang/MValue.java, src/mlang/backend_compilers/bir_to_java.ml
Java backend was only partially implemented, such that if compiling
without optimisations the backend breaks.
This PR aims to rectify that situation allowing the Java backend
to handle unoptimised code.
=> Fully implement java backend

dune-project, mlang.opam
=> Change license to SPDX format

.github/workflows/binary-releases.yml, .github/workflows/check_correctness.yml, .github/workflows/publish_doc.yml
=> Change ocaml setup version

mpp_specs/dgfip_base.mpp, src/mlang/backend_compilers/dgfip_gen_files.ml, src/mlang/m_frontend/mast.ml, src/mlang/m_frontend/mast_to_mir.ml, src/mlang/m_ir/mir.ml, src/mlang/m_ir/mir.mli, src/mlang/mpp_frontend/mpp_frontend.ml, src/mlang/mpp_ir/mpp_format.ml, src/mlang/mpp_ir/mpp_ir.ml, src/mlang/mpp_ir/mpp_ir_to_bir.ml
This dispatches M verifications to various functions definable in M++ specs through a new dedicated callable.
=> Verifications in specific chain functions

src/mlang/m_frontend/mast_to_mir.ml
This resolves #175.
The second commit is pure formatting, don't bother reviewing that.
=> Properly separate error raises in bulk verifications

src/mlang/backend_compilers/bir_to_dgfip_c.ml
Array access overlooked definess of target value. Not anymore.
=> Fix definess of array access in DGFIP backend

src/mlang/backend_compilers/bir_to_dgfip_c.ml
=> Fix vanishing not operand

examples/dgfip_c/const.h, examples/dgfip_c/enchain_static.c.inc, src/mlang/backend_ir/bir_interpreter.ml, src/mlang/backend_ir/bir_interpreter.mli, src/mlang/backend_ir/bir_number.ml, src/mlang/backend_ir/bir_number.mli, src/mlang/backend_ir/bir_roundops.ml, src/mlang/backend_ir/bir_roundops.mli, src/mlang/driver.ml, src/mlang/mpp_ir/mpp_ir_to_bir.ml, src/mlang/optimizing_ir/partial_evaluation.ml, src/mlang/test_framework/test_interpreter.ml, src/mlang/test_framework/test_interpreter.mli, src/mlang/utils/cli.ml, src/mlang/utils/cli.mli
The `my_arr` function has been updated in "recent" versions of the legacy compiler.
=> [DGFiP] Update my_arr function

src/mlang/optimizing_ir/partial_evaluation.ml
I spotted some semantic discrepancies on this pass and fixed them, hopefully.
=> Review and fixes on partial evaluation

Makefile, examples/dgfip_c/irdata.c, examples/dgfip_c/irdata.h, examples/dgfip_c/ml_primitif/common.ml, examples/dgfip_c/ml_primitif/m.ml, examples/dgfip_c/ml_primitif/main.ml, examples/dgfip_c/ml_primitif/stubs.c
This will make tests with ml code much faster.
Incidentally, it changes the signature of the TGV manipulation module to have a lot more side effects, which I believe reflects much more the aimed end result.
=> Use C bindings for TGV in ml code

src/mlang/optimizing_ir/partial_evaluation.ml
=> Fix tricky or semantics bug in partial evalutation

src/mlang/backend_compilers/bir_to_dgfip_c.ml, src/mlang/backend_compilers/bir_to_java.ml, src/mlang/backend_ir/bir.ml, src/mlang/backend_ir/bir.mli, src/mlang/backend_ir/bir_interface.ml, src/mlang/backend_ir/bir_interpreter.ml, src/mlang/backend_ir/format_bir.ml, src/mlang/mpp_ir/mpp_ir_to_bir.ml, src/mlang/optimizing_ir/dead_code_removal.ml, src/mlang/optimizing_ir/format_oir.ml, src/mlang/optimizing_ir/inlining.ml, src/mlang/optimizing_ir/oir.ml, src/mlang/optimizing_ir/oir.mli, src/mlang/optimizing_ir/partial_evaluation.ml
=> Remove some unnecessary infos from BIR

src/mlang/backend_compilers/decoupledExpr.ml, src/mlang/m_frontend/mast_to_mir.ml
closes #102 
At some point we should improve error/warning management in the code and through command line options.
=> New warning to report constant zero multiplications

src/mlang/backend_compilers/bir_to_dgfip_c.mli, src/mlang/backend_compilers/decoupledExpr.ml, src/mlang/backend_compilers/decoupledExpr.mli
And doc access. No semantic changes.
=> Some improvements in generator code legibility

src/mlang/m_frontend/mast_to_mir.ml, src/mlang/m_frontend/mparser.mly, src/mlang/m_ir/mir.ml, src/mlang/m_ir/mir.mli
=> Various code cleaning in mast_to_mir.ml (mostly)

examples/dgfip_c/ml_primitif/ml_driver/main.ml
=> Fix anomalies reporting in dump comparisons

src/mlang/backend_compilers/dgfip_gen_files.ml
Synchronised to MLanguage/brouillon-correctif#7 pull request.
=> Generate a struct.h file as the old C sources have been modified to require it

makefiles/c_backend.mk, makefiles/variables.mk, src/mlang/backend_compilers/dgfip_gen_files.ml, src/mlang/driver.ml, src/mlang/m_frontend/check_validity.ml, src/mlang/m_frontend/check_validity.mli, src/mlang/m_frontend/expand_macros.ml, src/mlang/m_frontend/mast.ml, src/mlang/m_frontend/mparser.mly, src/mlang/utils/cli.ml, src/mlang/utils/cli.mli, src/mlang/utils/dgfip_options.ml
Gestion de la sélections des règles via les annotation d'applications.
=> Applications

.github/workflows/binary-releases.yml, .github/workflows/check_correctness.yml, .github/workflows/publish_doc.yml
=> Fix cache@v1 deprecated

.github/workflows/publish_doc.yml
So the version number is correct
=> Enforce that the doc is generated after the release
