MLanguage/mlang

.github/workflows/trigger_gitlab_mirroring.yml

@denismerigoux as you suggested. I added a `sleep 30` to avoid the situation where Github thinks everything is good after it has performed its action only. Maybe we can reduce the sleep duration.

Trigger gitlab mirroring using an action

---

README.md

F* formalization was previously removed from project, this commits removes references to that file from the main README.

Remove references to nonexistant F* formalization

---

src/mlang/backend_compilers/bir_to_c.ml
src/mlang/backend_compilers/bir_to_python.ml
src/mlang/backend_ir/bir.ml
src/mlang/backend_ir/bir_instrumentation.ml
src/mlang/backend_ir/bir_interface.ml
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/backend_ir/format_bir.ml
src/mlang/m_frontend/mast_to_mvg.ml
src/mlang/m_ir/format_mir.ml
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir_dependency_graph.ml
src/mlang/m_ir/mir_interface.ml
src/mlang/m_ir/mir_typechecker.ml
src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/bir_to_oir.ml
src/mlang/optimizing_ir/dead_code_removal.ml
src/mlang/optimizing_ir/format_oir.ml
src/mlang/optimizing_ir/inlining.ml
src/mlang/optimizing_ir/oir.ml
src/mlang/optimizing_ir/partial_evaluation.ml
src/mlang/test_framework/test_interpreter.ml

This addresses issue #26.
For now it only applies to unoptimized compilation pipeline, and only changes the C backend.
For a reason yet unknown, it decreases efficiency and performance of the optimisations passes (yes, even without actually changing things). I hope a review could give some insight on this.

Split M code in rules

---

Dockerfile
Makefile
dune-project
mlang.opam
src/dune
src/mlang/dune
src/mlang/m_ir/mir.ml
src/mlang/optimizing_ir/partial_evaluation.ml

There were exactly *one* remaining occurrence of call to derived functions, that could be replaced with `Stdlib.compare` which should be semantically equivalent.

Removed obsolete ppx features

---

Makefile
Makefile.config.template
Makefile.include
README.md
examples/c/Makefile
examples/c/README.md
examples/c/backend_tests/Makefile
examples/dgfip_c/Makefile
examples/dgfip_c/backend_tests/Makefile

To use 'gcc', create a file 'Makefile.config' with 'C_COMPILER=gcc'. More options can be changed in that file, see comment in top `Makefile`.

Changes Makefiles to be able to use gcc

---

Makefile
src/dune
src/mlang/dune

The release profile currently active in the makefile for the
build-static target appears to override the static build thus breaking
the pre-built linux binary. This PR reverts that change.
It also removes the inclusion of the stdc++ library with appears to be
unused by MLang.
Finally this PR adds O3 level optimizations when the static profile is
active, increasing performance.
closes #91

Refactor dune files

---

examples/dgfip_c/Makefile
examples/dgfip_c/backend_tests/test_harness.c
examples/dgfip_c/m_error.c
examples/dgfip_c/m_error.h
src/mlang/backend_compilers/bir_to_dgfip_c.ml

The DGFiP backend doesn't currently return any information about the errors that occurred during calculation, just that an anomaly occurred. This PR aims to improve on that by returning information for all calculation error categories. 
Relates to #24

Improve anomaly handling

---

src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_compilers/bir_to_dgfip_c.mli
src/mlang/backend_compilers/dgfip_gen_files.ml
src/mlang/backend_compilers/dgfip_varid.ml
src/mlang/driver.ml
src/mlang/m_frontend/format_mast.mli
src/mlang/mpp_ir/mpp_ir_to_bir.ml

From #59, [relevant diff](https://github.com/MLanguage/mlang/pull/84/commits/6c6f2f84694edf41f1aace2a74e5ce02917ac56c).
This patch makes the dgfip backend produce code closer to the original compirateur. With this we should be able to build a calculette by fitting mlang in the current workflow.
Closes #22

Separation of definition flag and value computation in dgfip backend, and adaptation to current process

---

dune-project
mlang.opam

Following an update to Cmdliner v1.1.0, deprecation warnings now break
the macOS CI build.
Also Cmdliner is a direct dependancy of the project and should therefore be
explicitly mentionned in dune-project and mlang.opam files.

Set Cmdliner version to 1.0.4

---

src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/bir_to_oir.ml

This patch restrict rule code duplication to where it is actually needed. We don't need to duplicate code when it won't be optimized anyway.
It also makes transformation from Bir to Oir more robust to future structural changes, and speeds-up a bit the transfomation from Mpp to Bir.

Move rule instantiation to optimisation pass

---

.github/workflows/check_correctness.yml
dune-project
mlang.opam
src/mlang/driver.ml
src/mlang/utils/cli.ml
src/mlang/utils/cli.mli
src/mlang/utils/dgfip_options.ml

Cmdliner have release a new version 1.1.0 which has breaking changes,
this PR aims to update the version and change all the deprecated
function and module uses.
Closes issue #119

Update Cmdliner to v1.1.0

---

src/mlang/m_ir/mir_dependency_graph.ml

If a rule has no links to others through variable uses, it was "forgotten" by the dependency graph. This patch fixes that.

Fix disappearance of rules without dependencies in graph

---

src/mlang/backend_compilers/bir_to_c.ml
src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_compilers/bir_to_java.ml
src/mlang/backend_compilers/bir_to_python.ml
src/mlang/backend_ir/bir.ml
src/mlang/backend_ir/bir.mli
src/mlang/backend_ir/bir_instrumentation.ml
src/mlang/backend_ir/bir_instrumentation.mli
src/mlang/backend_ir/bir_interface.ml
src/mlang/backend_ir/bir_interface.mli
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/backend_ir/bir_interpreter.mli
src/mlang/backend_ir/format_bir.ml
src/mlang/backend_ir/format_bir.mli
src/mlang/m_frontend/mast_to_mir.ml
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir.mli
src/mlang/m_ir/mir_typechecker.ml
src/mlang/m_ir/mir_typechecker.mli
src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/dead_code_removal.ml
src/mlang/optimizing_ir/format_oir.ml
src/mlang/optimizing_ir/inlining.ml
src/mlang/optimizing_ir/oir.ml
src/mlang/optimizing_ir/oir.mli
src/mlang/optimizing_ir/partial_evaluation.ml
src/mlang/test_framework/test_interpreter.ml

This ought to straighten a bit the re-affectations semantics of Bir programs.
It needs more work to get rid of bugs and performance issues (and even more to smooth the whole thing up), drafting for now.

Unify SSA duplicated variables of Mir in Bir

---

mpp_specs/2018_6_7.mpp
mpp_specs/2019_8_0.mpp
mpp_specs/2020_6_5.mpp
mpp_specs/dgfip_base.mpp
src/mlang/backend_compilers/bir_to_java.ml
src/mlang/backend_compilers/dgfip_gen_files.ml
src/mlang/backend_ir/bir_interface.ml
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/driver.ml
src/mlang/m_frontend/format_mast.ml
src/mlang/m_frontend/format_mast.mli
src/mlang/m_frontend/mast.ml
src/mlang/m_frontend/mast_to_mir.ml
src/mlang/m_frontend/mast_to_mir.mli
src/mlang/m_frontend/mparser.mly
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir.mli
src/mlang/m_ir/mir_dependency_graph.ml
src/mlang/m_ir/mir_dependency_graph.mli
src/mlang/m_ir/mir_interface.ml
src/mlang/m_ir/mir_interface.mli
src/mlang/mpp_frontend/mpp_frontend.ml
src/mlang/mpp_ir/mpp_format.ml
src/mlang/mpp_ir/mpp_ir.ml
src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/dead_code_removal.ml

This uses tags on M rules definition to identify the subgraph of each "enchaineur" used by INTER files, including corrective ones.

Distinguish M code in separate chains

---

src/mlang/backend_compilers/bir_to_c.ml
src/mlang/backend_compilers/bir_to_java.ml
src/mlang/backend_ir/bir.ml
src/mlang/backend_ir/bir.mli
src/mlang/backend_ir/bir_interface.ml
src/mlang/backend_ir/bir_interface.mli
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir.mli
src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/dead_code_removal.ml
src/mlang/optimizing_ir/inlining.ml
src/mlang/test_framework/test_interpreter.ml
src/mlang/utils/dict.ml
src/mlang/utils/dict.mli

This is bound to change further in the futur, but is good enough for our immediate needs.
We now represent TGV variables as offset of a given TGV in the backend. It will be useful for copies handling.
Most changes in the backend code generation are the direct consequences of the existence of an offset upstream, making `var_indexes` useless. Reviewers shouldn't need to look too hard on those.

Change representation of backend variables

---

mpp_specs/dgfip_base.mpp
src/mlang/m_frontend/format_mast.ml
src/mlang/m_frontend/mast.ml
src/mlang/m_frontend/mast_to_mir.ml
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir_dependency_graph.ml
src/mlang/m_ir/mir_dependency_graph.mli
src/mlang/m_ir/mir_interface.ml

This patch support legacy specification of custom chains. A almost lost feature of the legacy compiler of which remain but a single occurrence in corrective code.
The way it works is a bit hackish as it build these custom sequence of rules from chains from tags and the coherency checks are as feeble as the tags themselves.
The graph analysis to build those chains might be useful for cheap optimisations later on (which might remove the usefulness of such custom chain, with some luck).

Support for custom M chains

---

examples/dgfip_c/backend_tests/Makefile
src/mlang/backend_compilers/bir_to_c.ml
src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_compilers/bir_to_java.ml
src/mlang/backend_compilers/bir_to_python.ml
src/mlang/backend_ir/bir.ml
src/mlang/backend_ir/bir.mli
src/mlang/backend_ir/bir_instrumentation.ml
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/backend_ir/bir_interpreter.mli
src/mlang/backend_ir/format_bir.ml
src/mlang/backend_ir/format_bir.mli
src/mlang/m_frontend/mast_to_mir.ml
src/mlang/m_ir/format_mir.ml
src/mlang/m_ir/mir.ml
src/mlang/m_ir/mir.mli
src/mlang/m_ir/mir_dependency_graph.ml
src/mlang/m_ir/mir_dependency_graph.mli
src/mlang/m_ir/mir_interface.ml
src/mlang/m_ir/mir_interface.mli
src/mlang/mpp_ir/mpp_ir_to_bir.ml
src/mlang/optimizing_ir/bir_to_oir.ml
src/mlang/optimizing_ir/dead_code_removal.ml
src/mlang/optimizing_ir/format_oir.ml
src/mlang/optimizing_ir/inlining.ml
src/mlang/optimizing_ir/oir.ml
src/mlang/optimizing_ir/oir.mli
src/mlang/optimizing_ir/partial_evaluation.ml

With this Mlang should generate the same files as the original compiler (modulo verifications for now).
Only in the DGFIP backend, I'm not sure this is something we want in the others.
I didn't notice a lot of change in compilation performances, though.

Generate rules in separate files corresponding to sources in DGFIP backend

---

examples/dgfip_c/ml_primitif/build.sh
src/mlang/backend_compilers/bir_to_dgfip_c.ml

This avoid generating debug macros in DGFIP backend test and should fix CI on master.
The flag used to trigger their generation was not the one used by the legacy compiler, counter-intuitively.

Remove traces from CI job

---

examples/java/src/com/mlang/MValue.java
src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_compilers/dgfip_varid.ml
src/mlang/backend_ir/bir_interpreter.ml

Closes #142 
`multimax` was though to be always defined, but it turns out it's only if any of its component is too.
Patched on top of #165 for simplicity, and silently dependent of #178.

Multimax semantics fix

---

Makefile
Makefile.include
examples/dgfip_c/ml_primitif/build.sh
src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_ir/format_bir.ml
src/mlang/optimizing_ir/bir_to_oir.ml
src/mlang/optimizing_ir/dead_code_removal.ml
src/mlang/optimizing_ir/format_oir.ml
src/mlang/optimizing_ir/inlining.ml
src/mlang/optimizing_ir/oir.ml
src/mlang/optimizing_ir/oir.mli
src/mlang/optimizing_ir/oir_optimizations.ml
src/mlang/optimizing_ir/partial_evaluation.ml

This allow a few simplification in the generated code.
Dead code and inlining have gone through the same treatment but have been disabled completely as it would be difficult to test their correctness (not that I think it can be correct in this context).

Rehabilitate partial evaluation as a per-function optimisation

---

examples/dgfip_c/backend_tests/Makefile
examples/java/backend_tests/src/com/mlang/TestHarness.java
examples/java/src/com/mlang/MValue.java
src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/optimizing_ir/partial_evaluation.ml

M functions min & max should return an undefined M value if both arguments are undefined, as it is the behaviour of the old tax system compiler.

Fix minmax result definition

---

src/mlang/backend_compilers/bir_to_dgfip_c.ml

To make sure the C doesn't interpret some values as integers.

Add point decimal to constants

---

examples/java/src/com/mlang/MValue.java
src/mlang/backend_compilers/bir_to_dgfip_c.ml

C and Java backend include a condition checking than a M cell table reading is in the table bound. The reference behaviour is to output a M undefined value if the queried cell has an index greater than the table last cell.
The backends where checking for index strictly greater than table size (logically, in practice this or the symmetrical check), as M table are indexed from 0, the last cell has size-1 index and the check should be greater or equal to size.

Fix guarding condition in accessing M table variable

---

.github/workflows/check_correctness.yml

With this we should avoid merging unformatted code to master, making later diffs saner.

Add CI formatting test

---

examples/dgfip_c/ml_primitif/build.sh
src/mlang/backend_compilers/bir_to_dgfip_c.ml

@mdurero found out that some recent changes on github runners would break CI through some stricter clang default options.
The culprit is a single global variable in the C generated code.

Fix CI failure on updated GH runners

---

src/mlang/backend_compilers/bir_to_dgfip_c.ml

If Mlang is called with an output filename including a path (say the relative `foo/bar.c`), previously:
- `bar.c` and auxiliary files like `irdata.c`were written in `foo/`
- rules and verification files like `chap-2.c` were written in the working directory of the call.
With this patch, all C source files are written in `foo/`

Fix generated ROV files path

---

examples/java/Makefile

Default mkdir does not like feeling useless.

Fix failure on java test with preexisting artefacts

---

src/mlang/backend_compilers/decoupledExpr.ml

C generation could lead to some incorrect code if the M input was not type-safe. This patch should handle that properly.
Bonus : less dubious conversions in the code.

Fix C type consistency

---

examples/dgfip_c/ml_primitif/Makefile

Simple fix:
- calculator C compilation step: build a file list excluding later driver files,
- driver C&ML compilation & linking step: remove object files to be produced by this step at its start.

Make possible to rebuild C backend without cleaning the build directory first.

---

Makefile
Makefile.config.template
README.md
examples/dgfip_c/ml_primitif/static/const.h
examples/dgfip_c/ml_primitif/static/enchain_static.c.inc
src/mlang/backend_compilers/decoupledExpr.ml
src/mlang/backend_compilers/dgfip_gen_files.ml
src/mlang/backend_ir/bir_interpreter.ml
src/mlang/backend_ir/bir_interpreter.mli
src/mlang/backend_ir/bir_roundops.ml
src/mlang/backend_ir/bir_roundops.mli
src/mlang/driver.ml
src/mlang/test_framework/test_interpreter.ml
src/mlang/test_framework/test_interpreter.mli
src/mlang/utils/cli.ml
src/mlang/utils/cli.mli

Work from @david-michel1, for mainframe interoperability and future maintainers mental sanity.
Must be linked to the corresponding merge request on the private repository with static DGFiP C interface.

Comparaison des flottants à epsilon près (interpréteur + backend C).

---

src/mlang/test_framework/parserMessages.messages

Now we have it, make it intelligible for end users writing the tests.

Parser messages and polish

---

m_ext/2023/cibles.m
makefiles/functions.mk
makefiles/variables.mk

Should we have a "default" m_ext source file that will be updated following the latest changes?
For now, using the same m_ext file (`cibles.m`) as for 2022. We should make that cleaner, even if it simply consists of copying & pasting in a 2023 directory

Add config options for year 2023 in the Makefiles

---

src/mlang/backend_compilers/bir_to_dgfip_c.ml
src/mlang/backend_compilers/dgfip_gen_files.ml
src/mlang/dgfip_m.ml
src/mlang/driver.ml

Basically:
- some constant renaming,
- ditch one FLG_MULTITHREAD in enchain generated code,
- new names for irdata members with context,
- add extern mathematical function in var.h,
- remove TAILLE_TOTALE,
- remove some _PROTS.

Renaming and prototype change for the Calculette memory refactor

---

Makefile
dune-project
makefiles/functions.mk
makefiles/mlang.mk

C’est le plus propre que j’ai pondu avec l’aide de David pour se brancher à ses makefiles.

Automatise un marquage de la version de l’exécutable par git-describe

---

makefiles/mlang.mk
makefiles/variables.mk
src/dune
src/main.ml
src/mlang/backend_compilers/dgfip_compir_files.ml
src/mlang/backend_compilers/dgfip_gen_files.ml
src/mlang/driver.ml
src/mlang/m_frontend/check_validity.ml
src/mlang/m_frontend/check_validity.mli
src/mlang/m_ir/com.mli
src/mlang/m_ir/mir_number.mli
src/mlang/m_ir/mir_roundops.mli
src/mlang/utils/errors.ml
src/mlang/utils/errors.mli
src/mlang/utils/strings.ml
src/mlang/utils/strings.mli

- Raise a warning if a variable is defined twice within the same rule
- Raise an error if a variable is defined in two different rules (within the same chaining). This brings back the same behaviour as the legacy compiler.
- Improve the error message for an auto-cycle (the warning typically happens if instructions within a rule are in the wrong order, so that a variable is used before being defined)

New errors and warnings

---

src/mlang/m_ir/mir_interpreter.ml
src/mlang/m_ir/mir_interpreter.mli
src/mlang/test_framework/test_interpreter.ml

Fuzzer tests before 2020 used 0.000000 as an expected value for 'undefined'. Since https://github.com/MLanguage/mlang/pull/262 this equivalence have been lost and make tests fails.
This PR adds more details on variable status after intepretation and accepts 'Undefined' as a correct value for 0.

Fix interpretation of undefined variables

---

makefiles/variables.mk

Updates the ir-calcul submodule to include the latest M code and updates the makefile accordingly
How to test : 
$  make clean build YEAR=2023 test_dgfip_c_backend

Adding tests of 2023
